version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: ct-db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER:-user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
      POSTGRES_DB: ${DB_NAME:-clinical_trust}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ct-backend
    restart: always
    environment:
      DATABASE_URL: "postgresql://${DB_USER:-user}:${DB_PASSWORD:-password}@db:5432/${DB_NAME:-clinical_trust}"
      PORT: 3001
      NEXT_PUBLIC_TENANT_ID: ${NEXT_PUBLIC_TENANT_ID:-test-tenant-123}
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -c "npx prisma generate && npx prisma db push --accept-data-loss && node dist/server.js"
    labels:
      - traefik.enable=true
      - traefik.docker.network=dokploy-network
      # Http configuration
      - traefik.http.routers.ct-backend.rule=Host(`core.carvalhodev.com.br`)
      - traefik.http.routers.ct-backend.entrypoints=web
      - traefik.http.routers.ct-backend.middlewares=redirect-to-https@file
      # Https configuration
      - traefik.http.routers.ct-backend-secure.rule=Host(`core.carvalhodev.com.br`)
      - traefik.http.routers.ct-backend-secure.entrypoints=websecure
      - traefik.http.routers.ct-backend-secure.tls.certresolver=letsencrypt
      # Service definition - A URL BATE NA PORTA DE DENTRO DO NODEJS (3001)
      - traefik.http.services.ct-backend.loadbalancer.server.port=3001
    networks:
      - dokploy-network
      - default

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-https://core.carvalhodev.com.br}
        NEXT_PUBLIC_TENANT_ID: ${NEXT_PUBLIC_TENANT_ID:-test-tenant-123}
    container_name: ct-frontend
    restart: always
    depends_on:
      - backend
    labels:
      - traefik.enable=true
      - traefik.docker.network=dokploy-network
      # Http configuration
      - traefik.http.routers.ct-frontend.rule=Host(`pet.carvalhodev.com.br`)
      - traefik.http.routers.ct-frontend.entrypoints=web
      - traefik.http.routers.ct-frontend.middlewares=redirect-to-https@file
      # Https configuration
      - traefik.http.routers.ct-frontend-secure.rule=Host(`pet.carvalhodev.com.br`)
      - traefik.http.routers.ct-frontend-secure.entrypoints=websecure
      - traefik.http.routers.ct-frontend-secure.tls.certresolver=letsencrypt
      # Next JS usa a porta 3000 por padrao!
      - traefik.http.services.ct-frontend.loadbalancer.server.port=3000
    networks:
      - dokploy-network
      - default

  mediamtx:
    image: bluenviron/mediamtx
    container_name: ct-mediamtx
    restart: always
    ports:
      - "8554:8554" # RTSP
      - "8888:8888" # HLS
      - "8889:8889" # WebRTC

networks:
  dokploy-network:
    external: true
